[package]
name = "gen"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
prettyplease = "0.2.19"
proc-macro2 = { version = "1.0.81", default-features = false }
quote = { version = "1.0.36", default-features = false }
regex = "1.10.4"
scraper = "0.19.0"
syn = { version = "2.0.60", features = ["extra-traits", "visit-mut"] }
syn-miette = "0.3.0"
ureq = "2.9.6"
owo-colors = "4.0.0"
