[package]
name = "gen"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
regex = "1.10.4"
scraper = "0.19.0"
ureq = "2.9.6"
